### ISSUE TITLE
Modificar tasks do makefile do leggo-geral

### ISSUE THREAD

**Issue by danielhmarinho** [analytics-ufcg/leggo-geral#78]
- [x] Verificar makefile atual e retirar a dependência do python para buildar as imagens;
- [x] O comando de build deve verificar se ja existe um arquivo de env nos repositórios e caso seja o sample deve criar um env a partir do que existe;
- [x] Corrigir criação dos volumes;
- [x] Subir dumps de banco para serem importados na construção do ambiente (api parlametria e api twitter);

Resultado esperado:
Comandos de build e up subirem o ambiente de forma completa, com bancos mínimos importados e sem nenhum erro ou procedimento adicional necessário.

**Comment by danielhmarinho** [comment]
@lorryaze como está o andamento da issue?

**Comment by lorryaze** [comment]
Eu comecei a estudar a issue e tentar mexer porém durante a sexta eu não consegui andar pois tive alguns compromissos, devo continuar mexendo durante o fds.

**Comment by lorryaze** [comment]
@danielhmarinho Hoje dando uma estudada no makefile e dando uma olhada no arquivo run fiquei na dúvida sobre o motivo de ser retirado a dependência do python já que ela é usada para executar o run.py que é onde os comando de build, up e etc estão setados, você poderia me explicar melhor? 

Outra dúvida que fiquei é se a correação dos volumes deve ser feita no makefile ou no run.py, já que o comando de criar volumes está no run.py.

**Comment by danielhmarinho** [comment]
@lorryaze vamos fazer o seguinte, a ideia era extrair esse script do run e tirar completamente a dependência do python, mas acho que pra um primeiro momento pode ficar complexo. Deixa a primeira tarefa em aberto e customiza os scripts atuais pra resolver os outros problemas
